### ISSUE TITLE
想请教下工程里面的FFmpeg静态库怎么编译的

### ISSUE THREAD

**Issue by LHMacCoder** [czqasngit/ffmpeg-player#2]
我用Homebrew安装FFmpeg，然后在安装路径下拷贝lib和include到我的工程里面，但是编译的时候报错，类似这种：

Showing All Issues
Undefined symbol: _FT_Done_Face
Undefined symbol: _FT_Done_FreeType
Undefined symbol: _FT_Done_Glyph
Undefined symbol: _FT_Get_Glyph
Undefined symbol: _FT_Get_Kerning
Undefined symbol: _FT_Glyph_Get_CBox
Undefined symbol: _FT_Glyph_StrokeBorder
Undefined symbol: _FT_Glyph_To_Bitmap
Undefined symbol: _FT_Init_FreeType
Undefined symbol: _FT_Load_Char
Undefined symbol: _FT_New_Face
Undefined symbol: _FT_Set_Char_Size

**Comment by czqasngit** [comment]
https://trac.ffmpeg.org/wiki/CompilationGuide/macOS
