### ISSUE TITLE
播放ape等音频文件崩溃，flv格式视屏画面卡主，无法正常播放

### ISSUE THREAD

**Issue by fineusing** [czqasngit/ffmpeg-player#4]
替换了你的ffmpeg库，然后播放ape,wav等音频文件都会崩溃，看了一下AuidoContext的codecContext->frame_size为0导致了异常，播放flv视屏画面卡主无法正常播放

**Comment by czqasngit** [comment]
你提供一下你播放的文件？你替换ffmpeg哪个版本？

**Comment by Robby0318** [comment]
> 你提供一下你播放的文件？你替换ffmpeg哪个版本？

ffmpeg 4.4,自己编译的，链接很多其他第三方的编解码库。
ape文件:

**Comment by Robby0318** [comment]
ffmpeg 4.4,自己编译的，链接很多其他第三方的编解码库,选择编译最小支持系统10.13。
ape文件:链接: https://pan.baidu.com/s/1gSqYY1uwx7lMyshHliH28w?pwd=wfwv 
flv文件:链接: https://pan.baidu.com/s/1K_joAfxb_5k7XL7Z-UpOHg?pwd=4jt3

**Comment by fineusing** [comment]
> 你提供一下你播放的文件？你替换ffmpeg哪个版本？

ffmpeg 4.4,自己编译的，链接很多其他第三方的编解码库,选择编译最小支持系统10.13。
ape文件:链接: https://pan.baidu.com/s/1gSqYY1uwx7lMyshHliH28w?pwd=wfwv
flv文件:链接: https://pan.baidu.com/s/1K_joAfxb_5k7XL7Z-UpOHg?pwd=4jt3

**Comment by czqasngit** [comment]
加我的微信yxbhr9527

**Comment by czqasngit** [comment]
I fixed ape crash error on Objective-C target without swift.
