### ISSUE TITLE
render  error ! green  screen

### ISSUE THREAD

**Issue by cherishloveyou** [czqasngit/ffmpeg-player#5]
Build  scucess, render error
Pleases help, i guess  it is not NV12 format, but i420 
is error render metal shaders?

**Comment by czqasngit** [comment]
Have some detail logs or error stack screenshot?

**Comment by cherishloveyou** [comment]
![image](https://user-images.githubusercontent.com/1764796/186158287-903b153e-4655-46f1-ad40-afb3d407b13b.png)
I test it with iPad rtsp stream not .mp4 file
