### ISSUE TITLE
Metal网格单元与线程组计算

### ISSUE THREAD

**Issue by welljobs** [czqasngit/ffmpeg-player#7]
博主你好，问个问题 我在iPhone手机上，视频是1280x720,这个线程组我按照最大32 * 16 视频只显示一小个窗口，我应该怎么计算这个线程组,不然就挂了
-[MTLDebugComputeCommandEncoder _validateThreadsPerThreadgroup:]:965: failed assertion `(threadsPerThreadgroup.width(40) * threadsPerThreadgroup.height(45) * threadsPerThreadgroup.depth(1))(1800) must be <= 512. (device threadgroup size limit)'
![7971680543881_ pic](https://user-images.githubusercontent.com/19242491/229702967-882bea6b-745d-4e14-96fd-f00f57f3ad0d.jpg)

https://user-images.githubusercontent.com/19242491/229703302-d4f78ef1-aaf8-4f2f-962b-f540d91a664e.mp4

**Comment by JohnWong** [comment]
> 博主你好，问个问题 我在iPhone手机上，视频是1280x720,这个线程组我按照最大32 * 16 视频只显示一小个窗口，我应该怎么计算这个线程组,不然就挂了 -[MTLDebugComputeCommandEncoder _validateThreadsPerThreadgroup:]:965: failed assertion `(threadsPerThreadgroup.width(40) * threadsPerThreadgroup.height(45) * threadsPerThreadgroup.depth(1))(1800) must be <= 512. (device threadgroup size limit)' ![7971680543881_ pic](https://user-images.githubusercontent.com/19242491/229702967-882bea6b-745d-4e14-96fd-f00f57f3ad0d.jpg)
> 
>  799_1680544267.mp4

参考这个文档计算 https://developer.apple.com/documentation/metal/compute_passes/calculating_threadgroup_and_grid_sizes
